services:
  # 后端服务
  web:
    build: .
    container_name: office_automation_web
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./static:/app/static

  # Redis 服务
  redis:
    image: redis:7-alpine
    container_name: office_automation_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: